#! /bin/sh
# Terminate already running bar instances
killall -q polybar
killall -q sxhkd
killall -q compton
killall -q mpd
pkill -f 'python.*wicd-client.py'
pkill -f 'python.*blueman-applet'
# Wait until the processes have been shut down
sleep 3

PATH=$HOME/.scripts:$HOME/.local/bin:$PATH
IS_OFFICE=255
IS_SALA=255

echo $PATH >> $HOME/.xsession-errors
echo $DISPLAY
echo $XAUTHORITY

xset +fp ~/.fonts/siji
xset +fp ~/.fonts/tewi
xset +fp ~/.fonts/ohsnap
xset +fp ~/.fonts/fontawesome
xset +fp ~/.fonts/terminesspowerline
xsetroot -cursor_name left_ptr

if test -z "$1"; then
    monitor-switch -w DP1=826751052 -w HDMI1=1128945228 -c office
    IS_OFFICE=$?
    monitor-switch -w HDMI1=16843009 -c sala
    IS_SALA=$?
fi

if test "$IS_OFFICE" -eq 0 ; then
    echo "Configurando para la oficina." >> $HOME/.xsession-errors
    bspc monitor HDMI1 -d 1 2 3
    bspc monitor DP1 -d 4 5 6
    bspc monitor eDP1 -d 7 8 9
elif test "$IS_SALA" -eq 0 ; then
    echo "Configurando para la sala." >> $HOME/.xsession-errors
    bspc monitor HDMI1 -d 1 2 3
    bspc monitor eDP1 -d 4 5 6 7 8 9 0
else
    echo "Configuración genérica." >> $HOME/.xsession-errors
    bspc monitor -d 1 2 3 4 5
fi

echo IS_SALA "$IS_SALA" >> $HOME/.xsession-errors ;
echo IS_OFFICE "$IS_OFFICE" >> $HOME/.xsession-errors ;

sxhkd &
#compton &
#nitrogen --restore
# runhaskell -XFlexibleContexts -i$HOME/.scripts/lemonbar $HOME/.scripts/lemonbar/bar.hs &
wicd-gtk -t &
blueman-applet 2>&1 > /dev/null &
mpd

if test -f $HOME/.local/bin/mopidy; then
    mopidy 2>&1 > /dev/null &
fi

if test -f $HOME/.local/bin/beet; then
    beet web 2>&1 > /dev/null &
fi

bspc config border_width         1
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc desktop 3 -f
polybar example 2>&1 &
feh --bg-fill $HOME/.backgrounds/joystick.jpg

ps aux
