#! /bin/sh
# Terminate already running bar instances
killall -q polybar
killall cd-q sxhkd
killall -q compton
killall -q mpd
pkill -f 'python.*blueman-applet'
killall -q nm-applet
# Wait until the processes have been shut down
sleep 3

PATH=$HOME/.scripts:$HOME/.local/bin:$PATH
IS_OFFICE=255
IS_SALA=255

echo $PATH >> $HOME/.xsession-errors
echo $DISPLAY
echo $XAUTHORITY

xset +fp ~/.fonts/siji
xset +fp ~/.fonts/tewi
xset +fp ~/.fonts/ohsnap
xset +fp ~/.fonts/fontawesome
xset +fp ~/.fonts/terminesspowerline
xsetroot -cursor_name left_ptr

sxhkd &
compton &
#nitrogen --restore
# runhaskell -XFlexibleContexts -i$HOME/.scripts/lemonbar $HOME/.scripts/lemonbar/bar.hs &
blueman-applet 2>&1 > /dev/null &
#mpd
nm-applet 2>&1 > /dev/null &

if test -f $HOME/.local/bin/mopidy; then
    mopidy 2>&1 > /dev/null &
fi

if test -f $HOME/.local/bin/beet; then
    beet web 2>&1 > /dev/null &
fi

bspc config border_width         1
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


if test -z "$1"; then
  if monitor-switch -w DP1=1095780169 -w HDMI1=1128945228 -c office; then
    echo "Configurando para la oficina."
    bspc monitor HDMI1 -d 1 2 3
    bspc monitor DP1 -d 4 5 6
    bspc monitor eDP1 -d 7 8 9
    feh --bg-tile $HOME/.backgrounds/Tile/bamboo.png
  elif monitor-switch -w HDMI1=1128945228 -c office3; then
    echo "Configurando para la oficina 2."
    bspc monitor HDMI1 -d 1 2 3 4 5
    bspc monitor eDP1 -d 6 7 8 9 0
    feh --bg-tile $HOME/.backgrounds/Tile/bamboo.png
  elif monitor-switch -w HDMI1=16843009 -c sala; then
    echo "Configurando para la sala."
    bspc monitor HDMI1 -d 1 2 3
    bspc monitor eDP1 -d 4 5 6 7 8 9 0
    feh --bg-tile $HOME/.backgrounds/joystick.jpg
  elif monitor-switch -w HDMI1=1178023509 -c home; then
    echo "Configurando para el cuarto ."
    bspc monitor HDMI1 -d 1 2 3
    bspc monitor eDP1 -d 4 5 6 7 8 9 0
    feh --bg-tile $HOME/.backgrounds/Tile/tile_eggs00.png
    polybar home 2>&1 &
  elif monitor-switch -w HDMI1=1515868723 -c office4; then
    echo "Configurando para Altuve's office."
    bspc monitor HDMI1 -d 1 2 3 4 5
    bspc monitor eDP1 -d 6 7 8 9 0
    feh --bg-tile $HOME/.backgrounds/Tile/tile_eggs00.png
    polybar home 2>&1 &
  else
    echo "Configuración genérica."
    #xrandr --output eDP1 --mode 1366x768 --primary
    #xrandr --output DP1 --mode 1360x768 --left-of eDP1
    #bspc monitor DP1 -d 1 2 3 
    bspc monitor eDP1 -d 1 2 3 4 5
    feh --bg-tile $HOME/.backgrounds/Tile/tile_eggs00.png
  fi
fi

polybar example 2>&1 &

bspc desktop 4 -f

#xmodmap -e "pointer = 3 2 1"
