#! /bin/sh

export PATH=$HOME/.local/bin:$PATH
xset +fp ~/.fonts/siji
xset +fp ~/.fonts/tewi
xset +fp ~/.fonts/ohsnap
xset +fp ~/.fonts/fontawesome
xset +fp ~/.fonts/terminesspowerline


sxhkd &
compton &
nitrogen --restore
bspc monitor -d I II III IV V
runhaskell -XFlexibleContexts -i$HOME/.scripts/lemonbar $HOME/.scripts/lemonbar/bar.hs &
wicd-gtk -t &
blueman-applet 2>&1 > /dev/null &

if [ -x ~/.local/bin/mopidy ]; then
    mopidy 2>&1 > /dev/null &
fi

if [ -x ~/.local/bin/beet ]; then
    beet web 2>&1 > /dev/null &
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc desktop III -f
